# agent-java-goose: Java language image with Goose runtime.
#
# Extends agent-base-goose with JDK 21 and Maven for Java
# migration and development workloads.
#
# TODO: This is a placeholder. Toolchain installation will be added
# as part of Stream 4 (Base Image).

FROM quay.io/konveyor/agent-base-goose:latest

# TODO: Install JDK 21
# RUN microdnf install -y java-21-openjdk-devel && microdnf clean all

# TODO: Install Maven
# RUN microdnf install -y maven && microdnf clean all
