---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - konveyor.io
  resources:
  - skillcards
  - skillcollections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konveyor.io
  resources:
  - skillcards/finalizers
  - skillcollections/finalizers
  verbs:
  - update
- apiGroups:
  - konveyor.io
  resources:
  - skillcards/status
  - skillcollections/status
  verbs:
  - get
  - patch
  - update
