# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and target namespace.
# It should be run by config/default
resources:
- bases/konveyor.io_skillcards.yaml
- bases/konveyor.io_skillcollections.yaml
- bases/konveyor.io_gateways.yaml
- bases/konveyor.io_agents.yaml
- bases/konveyor.io_agentruns.yaml
- bases/konveyor.io_agentworkflows.yaml
- bases/konveyor.io_agentworkflowruns.yaml
#+kubebuilder:scaffold:crdkustomizeresource
