name: E2E Tests

on:
  push:
  pull_request:

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Install kind
        env:
          KIND_VERSION: v0.27.0
        run: |
          curl -fLo ./kind --retry 5 --retry-delay 10 --retry-all-errors \
            "https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-$(go env GOARCH)"
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install Helm
        run: |
          curl -fL --retry 5 --retry-delay 10 --retry-all-errors \
            https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Running e2e
        run: make e2e
